// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/UkralStul/graphql-comments-service/internal/domain"
)

type CommentConnection struct {
	Edges    []*CommentEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Cursor string          `json:"cursor"`
	Node   *domain.Comment `json:"node"`
}

type Mutation struct {
}

type NewComment struct {
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
	AuthorID string  `json:"authorId"`
	Content  string  `json:"content"`
}

type NewPost struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	AuthorID string `json:"authorId"`
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type Subscription struct {
}
